/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AbsenceDayOffRequestsAcceptRequestRequest
 */
public class AbsenceDayOffRequestsAcceptRequestRequestTest {
    private final AbsenceDayOffRequestsAcceptRequestRequest model = new AbsenceDayOffRequestsAcceptRequestRequest();

    /**
     * Model tests for AbsenceDayOffRequestsAcceptRequestRequest
     */
    @Test
    public void testAbsenceDayOffRequestsAcceptRequestRequest() {
        // TODO: test AbsenceDayOffRequestsAcceptRequestRequest
    }

    /**
     * Test the property 'managerId'
     */
    @Test
    public void managerIdTest() {
        // TODO: test managerId
    }

    /**
     * Test the property 'resolutionComment'
     */
    @Test
    public void resolutionCommentTest() {
        // TODO: test resolutionComment
    }

}
