/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CheckValidationListByEmployeesAndStatusResponseDataInnerEmployee;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CheckValidationListByEmployeesAndStatusResponseDataInner
 */
public class CheckValidationListByEmployeesAndStatusResponseDataInnerTest {
    private final CheckValidationListByEmployeesAndStatusResponseDataInner model = new CheckValidationListByEmployeesAndStatusResponseDataInner();

    /**
     * Model tests for CheckValidationListByEmployeesAndStatusResponseDataInner
     */
    @Test
    public void testCheckValidationListByEmployeesAndStatusResponseDataInner() {
        // TODO: test CheckValidationListByEmployeesAndStatusResponseDataInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'employee'
     */
    @Test
    public void employeeTest() {
        // TODO: test employee
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'lastSent'
     */
    @Test
    public void lastSentTest() {
        // TODO: test lastSent
    }

    /**
     * Test the property 'timesSent'
     */
    @Test
    public void timesSentTest() {
        // TODO: test timesSent
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
