/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ContractsGetCurrentContractByEmployeeIdResponseDataContractType;
import com.konfigthis.client.model.ContractsGetCurrentContractByEmployeeIdResponseDataDegree;
import com.konfigthis.client.model.ContractsGetCurrentContractByEmployeeIdResponseDataHolidays;
import com.konfigthis.client.model.ContractsGetCurrentContractByEmployeeIdResponseDataJobCharge;
import com.konfigthis.client.model.ContractsGetCurrentContractByEmployeeIdResponseDataTrialPeriod;
import com.konfigthis.client.model.ContractsGetCurrentContractByEmployeeIdResponseDataWorkdayType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ContractsGetCurrentContractByEmployeeIdResponseData
 */
public class ContractsGetCurrentContractByEmployeeIdResponseDataTest {
    private final ContractsGetCurrentContractByEmployeeIdResponseData model = new ContractsGetCurrentContractByEmployeeIdResponseData();

    /**
     * Model tests for ContractsGetCurrentContractByEmployeeIdResponseData
     */
    @Test
    public void testContractsGetCurrentContractByEmployeeIdResponseData() {
        // TODO: test ContractsGetCurrentContractByEmployeeIdResponseData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'jobCharge'
     */
    @Test
    public void jobChargeTest() {
        // TODO: test jobCharge
    }

    /**
     * Test the property 'workdayType'
     */
    @Test
    public void workdayTypeTest() {
        // TODO: test workdayType
    }

    /**
     * Test the property 'contractType'
     */
    @Test
    public void contractTypeTest() {
        // TODO: test contractType
    }

    /**
     * Test the property 'degree'
     */
    @Test
    public void degreeTest() {
        // TODO: test degree
    }

    /**
     * Test the property 'agreement'
     */
    @Test
    public void agreementTest() {
        // TODO: test agreement
    }

    /**
     * Test the property 'startAt'
     */
    @Test
    public void startAtTest() {
        // TODO: test startAt
    }

    /**
     * Test the property 'endAt'
     */
    @Test
    public void endAtTest() {
        // TODO: test endAt
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'trialPeriod'
     */
    @Test
    public void trialPeriodTest() {
        // TODO: test trialPeriod
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'socialSecurityNumber'
     */
    @Test
    public void socialSecurityNumberTest() {
        // TODO: test socialSecurityNumber
    }

    /**
     * Test the property 'holidays'
     */
    @Test
    public void holidaysTest() {
        // TODO: test holidays
    }

}
