/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeDepartmentAssignationsUnassignResponseMeta
 */
public class EmployeeDepartmentAssignationsUnassignResponseMetaTest {
    private final EmployeeDepartmentAssignationsUnassignResponseMeta model = new EmployeeDepartmentAssignationsUnassignResponseMeta();

    /**
     * Model tests for EmployeeDepartmentAssignationsUnassignResponseMeta
     */
    @Test
    public void testEmployeeDepartmentAssignationsUnassignResponseMeta() {
        // TODO: test EmployeeDepartmentAssignationsUnassignResponseMeta
    }

    /**
     * Test the property 'currentPage'
     */
    @Test
    public void currentPageTest() {
        // TODO: test currentPage
    }

    /**
     * Test the property 'lastPage'
     */
    @Test
    public void lastPageTest() {
        // TODO: test lastPage
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'perPage'
     */
    @Test
    public void perPageTest() {
        // TODO: test perPage
    }

}
