/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeAssignationsRolesAssignRoleRequest
 */
public class EmployeeAssignationsRolesAssignRoleRequestTest {
    private final EmployeeAssignationsRolesAssignRoleRequest model = new EmployeeAssignationsRolesAssignRoleRequest();

    /**
     * Model tests for EmployeeAssignationsRolesAssignRoleRequest
     */
    @Test
    public void testEmployeeAssignationsRolesAssignRoleRequest() {
        // TODO: test EmployeeAssignationsRolesAssignRoleRequest
    }

    /**
     * Test the property 'roleId'
     */
    @Test
    public void roleIdTest() {
        // TODO: test roleId
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'entityAffectedId'
     */
    @Test
    public void entityAffectedIdTest() {
        // TODO: test entityAffectedId
    }

}
