/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.EmployeeOfficeAssignationsAssignEmployeeToOfficeResponseDataEmployee;
import com.konfigthis.client.model.OfficesGetAllResponseDataInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EmployeeOfficeAssignationsAssignEmployeeToOfficeResponseData
 */
public class EmployeeOfficeAssignationsAssignEmployeeToOfficeResponseDataTest {
    private final EmployeeOfficeAssignationsAssignEmployeeToOfficeResponseData model = new EmployeeOfficeAssignationsAssignEmployeeToOfficeResponseData();

    /**
     * Model tests for EmployeeOfficeAssignationsAssignEmployeeToOfficeResponseData
     */
    @Test
    public void testEmployeeOfficeAssignationsAssignEmployeeToOfficeResponseData() {
        // TODO: test EmployeeOfficeAssignationsAssignEmployeeToOfficeResponseData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'employee'
     */
    @Test
    public void employeeTest() {
        // TODO: test employee
    }

    /**
     * Test the property 'office'
     */
    @Test
    public void officeTest() {
        // TODO: test office
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
