/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.RecruitmentCreateCandidateResponseDataVacancyCategory;
import com.konfigthis.client.model.RecruitmentCreateCandidateResponseDataVacancyLocationVacancy;
import com.konfigthis.client.model.RecruitmentCreateCandidateResponseDataVacancyScheduleType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for RecruitmentCreateCandidateResponseDataVacancy
 */
public class RecruitmentCreateCandidateResponseDataVacancyTest {
    private final RecruitmentCreateCandidateResponseDataVacancy model = new RecruitmentCreateCandidateResponseDataVacancy();

    /**
     * Model tests for RecruitmentCreateCandidateResponseDataVacancy
     */
    @Test
    public void testRecruitmentCreateCandidateResponseDataVacancy() {
        // TODO: test RecruitmentCreateCandidateResponseDataVacancy
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'companyId'
     */
    @Test
    public void companyIdTest() {
        // TODO: test companyId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'department'
     */
    @Test
    public void departmentTest() {
        // TODO: test department
    }

    /**
     * Test the property 'contactType'
     */
    @Test
    public void contactTypeTest() {
        // TODO: test contactType
    }

    /**
     * Test the property 'experience'
     */
    @Test
    public void experienceTest() {
        // TODO: test experience
    }

    /**
     * Test the property 'createdById'
     */
    @Test
    public void createdByIdTest() {
        // TODO: test createdById
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'openedAt'
     */
    @Test
    public void openedAtTest() {
        // TODO: test openedAt
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property '_public'
     */
    @Test
    public void _publicTest() {
        // TODO: test _public
    }

    /**
     * Test the property 'locationVacancy'
     */
    @Test
    public void locationVacancyTest() {
        // TODO: test locationVacancy
    }

    /**
     * Test the property 'scheduleType'
     */
    @Test
    public void scheduleTypeTest() {
        // TODO: test scheduleType
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

}
