/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.VacationConfigurationsListConfigurationsResponseDataInnerNotAllowedDateRangesInner;
import com.konfigthis.client.model.VacationDayOffRequestsRejectRequestResponseDataVacationCalendarVacationConfigurationCompany;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VacationDayOffRequestsRejectRequestResponseDataVacationCalendarVacationConfiguration
 */
public class VacationDayOffRequestsRejectRequestResponseDataVacationCalendarVacationConfigurationTest {
    private final VacationDayOffRequestsRejectRequestResponseDataVacationCalendarVacationConfiguration model = new VacationDayOffRequestsRejectRequestResponseDataVacationCalendarVacationConfiguration();

    /**
     * Model tests for VacationDayOffRequestsRejectRequestResponseDataVacationCalendarVacationConfiguration
     */
    @Test
    public void testVacationDayOffRequestsRejectRequestResponseDataVacationCalendarVacationConfiguration() {
        // TODO: test VacationDayOffRequestsRejectRequestResponseDataVacationCalendarVacationConfiguration
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'employeeRequestEnabled'
     */
    @Test
    public void employeeRequestEnabledTest() {
        // TODO: test employeeRequestEnabled
    }

    /**
     * Test the property 'needsValidation'
     */
    @Test
    public void needsValidationTest() {
        // TODO: test needsValidation
    }

    /**
     * Test the property 'company'
     */
    @Test
    public void companyTest() {
        // TODO: test company
    }

    /**
     * Test the property 'dayType'
     */
    @Test
    public void dayTypeTest() {
        // TODO: test dayType
    }

    /**
     * Test the property 'maxDaysOff'
     */
    @Test
    public void maxDaysOffTest() {
        // TODO: test maxDaysOff
    }

    /**
     * Test the property 'isDefault'
     */
    @Test
    public void isDefaultTest() {
        // TODO: test isDefault
    }

    /**
     * Test the property 'notAllowedDateRanges'
     */
    @Test
    public void notAllowedDateRangesTest() {
        // TODO: test notAllowedDateRanges
    }

    /**
     * Test the property 'creationDateNextYear'
     */
    @Test
    public void creationDateNextYearTest() {
        // TODO: test creationDateNextYear
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

}
