/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.VacationDayOffRequestsRejectRequestResponseData;
import com.konfigthis.client.model.VacationDayOffRequestsRejectRequestResponseMeta;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VacationDayOffRequestsRejectRequestResponse
 */
public class VacationDayOffRequestsRejectRequestResponseTest {
    private final VacationDayOffRequestsRejectRequestResponse model = new VacationDayOffRequestsRejectRequestResponse();

    /**
     * Model tests for VacationDayOffRequestsRejectRequestResponse
     */
    @Test
    public void testVacationDayOffRequestsRejectRequestResponse() {
        // TODO: test VacationDayOffRequestsRejectRequestResponse
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

}
