/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.VacationCalendarsCreateNewCalendarRequestDaysOffInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VacationDayOffRequestsCreateRequestRequest
 */
public class VacationDayOffRequestsCreateRequestRequestTest {
    private final VacationDayOffRequestsCreateRequestRequest model = new VacationDayOffRequestsCreateRequestRequest();

    /**
     * Model tests for VacationDayOffRequestsCreateRequestRequest
     */
    @Test
    public void testVacationDayOffRequestsCreateRequestRequest() {
        // TODO: test VacationDayOffRequestsCreateRequestRequest
    }

    /**
     * Test the property 'employeeId'
     */
    @Test
    public void employeeIdTest() {
        // TODO: test employeeId
    }

    /**
     * Test the property 'calendarId'
     */
    @Test
    public void calendarIdTest() {
        // TODO: test calendarId
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'daysOff'
     */
    @Test
    public void daysOffTest() {
        // TODO: test daysOff
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

}
