/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.VacationCalendarsListCalendarsResponseDataInnerDaysOffInner;
import com.konfigthis.client.model.VacationDayOffRequestsCreateRequestResponseDataEmployee;
import com.konfigthis.client.model.VacationDayOffRequestsCreateRequestResponseDataVacationCalendar;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VacationDayOffRequestsCreateRequestResponseData
 */
public class VacationDayOffRequestsCreateRequestResponseDataTest {
    private final VacationDayOffRequestsCreateRequestResponseData model = new VacationDayOffRequestsCreateRequestResponseData();

    /**
     * Model tests for VacationDayOffRequestsCreateRequestResponseData
     */
    @Test
    public void testVacationDayOffRequestsCreateRequestResponseData() {
        // TODO: test VacationDayOffRequestsCreateRequestResponseData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'vacationCalendar'
     */
    @Test
    public void vacationCalendarTest() {
        // TODO: test vacationCalendar
    }

    /**
     * Test the property 'employee'
     */
    @Test
    public void employeeTest() {
        // TODO: test employee
    }

    /**
     * Test the property 'daysOff'
     */
    @Test
    public void daysOffTest() {
        // TODO: test daysOff
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'resolutionComment'
     */
    @Test
    public void resolutionCommentTest() {
        // TODO: test resolutionComment
    }

    /**
     * Test the property 'resolvedAt'
     */
    @Test
    public void resolvedAtTest() {
        // TODO: test resolvedAt
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

}
