/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.WorkEntriesCreateNewEntryResponseDataEmployee;
import com.konfigthis.client.model.WorkEntriesCreateNewEntryResponseDataWorkEntryIn;
import com.konfigthis.client.model.WorkEntriesCreateNewEntryResponseDataWorkEntryOut;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkEntriesCreateNewEntryResponseData
 */
public class WorkEntriesCreateNewEntryResponseDataTest {
    private final WorkEntriesCreateNewEntryResponseData model = new WorkEntriesCreateNewEntryResponseData();

    /**
     * Model tests for WorkEntriesCreateNewEntryResponseData
     */
    @Test
    public void testWorkEntriesCreateNewEntryResponseData() {
        // TODO: test WorkEntriesCreateNewEntryResponseData
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'workCheckTypeId'
     */
    @Test
    public void workCheckTypeIdTest() {
        // TODO: test workCheckTypeId
    }

    /**
     * Test the property 'employee'
     */
    @Test
    public void employeeTest() {
        // TODO: test employee
    }

    /**
     * Test the property 'workEntryType'
     */
    @Test
    public void workEntryTypeTest() {
        // TODO: test workEntryType
    }

    /**
     * Test the property 'workEntryIn'
     */
    @Test
    public void workEntryInTest() {
        // TODO: test workEntryIn
    }

    /**
     * Test the property 'workEntryOut'
     */
    @Test
    public void workEntryOutTest() {
        // TODO: test workEntryOut
    }

    /**
     * Test the property 'workedSeconds'
     */
    @Test
    public void workedSecondsTest() {
        // TODO: test workedSeconds
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

}
