/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AbsenceCalendarsCreateCalendarRequestDaysOffInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * AbsenceCalendarsCreateCalendarRequest
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class AbsenceCalendarsCreateCalendarRequest {
  public static final String SERIALIZED_NAME_EMPLOYEE_ID = "employeeId";
  @SerializedName(SERIALIZED_NAME_EMPLOYEE_ID)
  private UUID employeeId;

  public static final String SERIALIZED_NAME_ABSENCE_TYPE_ID = "absenceTypeId";
  @SerializedName(SERIALIZED_NAME_ABSENCE_TYPE_ID)
  private UUID absenceTypeId;

  public static final String SERIALIZED_NAME_YEAR = "year";
  @SerializedName(SERIALIZED_NAME_YEAR)
  private Integer year;

  public static final String SERIALIZED_NAME_DAYS_OFF = "daysOff";
  @SerializedName(SERIALIZED_NAME_DAYS_OFF)
  private List<AbsenceCalendarsCreateCalendarRequestDaysOffInner> daysOff = new ArrayList<>();

  public AbsenceCalendarsCreateCalendarRequest() {
  }

  public AbsenceCalendarsCreateCalendarRequest employeeId(UUID employeeId) {
    
    
    
    
    this.employeeId = employeeId;
    return this;
  }

   /**
   * Get employeeId
   * @return employeeId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public UUID getEmployeeId() {
    return employeeId;
  }


  public void setEmployeeId(UUID employeeId) {
    
    
    
    this.employeeId = employeeId;
  }


  public AbsenceCalendarsCreateCalendarRequest absenceTypeId(UUID absenceTypeId) {
    
    
    
    
    this.absenceTypeId = absenceTypeId;
    return this;
  }

   /**
   * Get absenceTypeId
   * @return absenceTypeId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public UUID getAbsenceTypeId() {
    return absenceTypeId;
  }


  public void setAbsenceTypeId(UUID absenceTypeId) {
    
    
    
    this.absenceTypeId = absenceTypeId;
  }


  public AbsenceCalendarsCreateCalendarRequest year(Integer year) {
    
    
    
    
    this.year = year;
    return this;
  }

   /**
   * Get year
   * @return year
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "2023", required = true, value = "")

  public Integer getYear() {
    return year;
  }


  public void setYear(Integer year) {
    
    
    
    this.year = year;
  }


  public AbsenceCalendarsCreateCalendarRequest daysOff(List<AbsenceCalendarsCreateCalendarRequestDaysOffInner> daysOff) {
    
    
    
    
    this.daysOff = daysOff;
    return this;
  }

  public AbsenceCalendarsCreateCalendarRequest addDaysOffItem(AbsenceCalendarsCreateCalendarRequestDaysOffInner daysOffItem) {
    this.daysOff.add(daysOffItem);
    return this;
  }

   /**
   * array of AbsenceCalendarDayOff
   * @return daysOff
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "array of AbsenceCalendarDayOff")

  public List<AbsenceCalendarsCreateCalendarRequestDaysOffInner> getDaysOff() {
    return daysOff;
  }


  public void setDaysOff(List<AbsenceCalendarsCreateCalendarRequestDaysOffInner> daysOff) {
    
    
    
    this.daysOff = daysOff;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the AbsenceCalendarsCreateCalendarRequest instance itself
   */
  public AbsenceCalendarsCreateCalendarRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AbsenceCalendarsCreateCalendarRequest absenceCalendarsCreateCalendarRequest = (AbsenceCalendarsCreateCalendarRequest) o;
    return Objects.equals(this.employeeId, absenceCalendarsCreateCalendarRequest.employeeId) &&
        Objects.equals(this.absenceTypeId, absenceCalendarsCreateCalendarRequest.absenceTypeId) &&
        Objects.equals(this.year, absenceCalendarsCreateCalendarRequest.year) &&
        Objects.equals(this.daysOff, absenceCalendarsCreateCalendarRequest.daysOff)&&
        Objects.equals(this.additionalProperties, absenceCalendarsCreateCalendarRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(employeeId, absenceTypeId, year, daysOff, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AbsenceCalendarsCreateCalendarRequest {\n");
    sb.append("    employeeId: ").append(toIndentedString(employeeId)).append("\n");
    sb.append("    absenceTypeId: ").append(toIndentedString(absenceTypeId)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    daysOff: ").append(toIndentedString(daysOff)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("employeeId");
    openapiFields.add("absenceTypeId");
    openapiFields.add("year");
    openapiFields.add("daysOff");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("employeeId");
    openapiRequiredFields.add("absenceTypeId");
    openapiRequiredFields.add("year");
    openapiRequiredFields.add("daysOff");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to AbsenceCalendarsCreateCalendarRequest
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!AbsenceCalendarsCreateCalendarRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AbsenceCalendarsCreateCalendarRequest is not found in the empty JSON string", AbsenceCalendarsCreateCalendarRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AbsenceCalendarsCreateCalendarRequest.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("employeeId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `employeeId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("employeeId").toString()));
      }
      if (!jsonObj.get("absenceTypeId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `absenceTypeId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("absenceTypeId").toString()));
      }
      // ensure the json data is an array
      if (!jsonObj.get("daysOff").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `daysOff` to be an array in the JSON string but got `%s`", jsonObj.get("daysOff").toString()));
      }

      JsonArray jsonArraydaysOff = jsonObj.getAsJsonArray("daysOff");
      // validate the required field `daysOff` (array)
      for (int i = 0; i < jsonArraydaysOff.size(); i++) {
        AbsenceCalendarsCreateCalendarRequestDaysOffInner.validateJsonObject(jsonArraydaysOff.get(i).getAsJsonObject());
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AbsenceCalendarsCreateCalendarRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AbsenceCalendarsCreateCalendarRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AbsenceCalendarsCreateCalendarRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AbsenceCalendarsCreateCalendarRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<AbsenceCalendarsCreateCalendarRequest>() {
           @Override
           public void write(JsonWriter out, AbsenceCalendarsCreateCalendarRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public AbsenceCalendarsCreateCalendarRequest read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             AbsenceCalendarsCreateCalendarRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AbsenceCalendarsCreateCalendarRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AbsenceCalendarsCreateCalendarRequest
  * @throws IOException if the JSON string is invalid with respect to AbsenceCalendarsCreateCalendarRequest
  */
  public static AbsenceCalendarsCreateCalendarRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AbsenceCalendarsCreateCalendarRequest.class);
  }

 /**
  * Convert an instance of AbsenceCalendarsCreateCalendarRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

