/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.HolidayCalendarsCreateNewCalendarResponseDataDayOffInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * HolidayCalendarsCreateNewCalendarResponseData
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class HolidayCalendarsCreateNewCalendarResponseData {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_COMPANY_ID = "companyId";
  @SerializedName(SERIALIZED_NAME_COMPANY_ID)
  private UUID companyId;

  public static final String SERIALIZED_NAME_DAY_OFF = "dayOff";
  @SerializedName(SERIALIZED_NAME_DAY_OFF)
  private List<HolidayCalendarsCreateNewCalendarResponseDataDayOffInner> dayOff = null;

  public static final String SERIALIZED_NAME_TYPE_ID = "typeId";
  @SerializedName(SERIALIZED_NAME_TYPE_ID)
  private UUID typeId;

  public static final String SERIALIZED_NAME_DEFAULT = "default";
  @SerializedName(SERIALIZED_NAME_DEFAULT)
  private Boolean _default;

  public HolidayCalendarsCreateNewCalendarResponseData() {
  }

  public HolidayCalendarsCreateNewCalendarResponseData id(UUID id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "37acce51-a7e3-498d-b235-5ae8f8682078", value = "")

  public UUID getId() {
    return id;
  }


  public void setId(UUID id) {
    
    
    
    this.id = id;
  }


  public HolidayCalendarsCreateNewCalendarResponseData name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * The name of the holidays
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Zona Valencia", value = "The name of the holidays")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public HolidayCalendarsCreateNewCalendarResponseData companyId(UUID companyId) {
    
    
    
    
    this.companyId = companyId;
    return this;
  }

   /**
   * Get companyId
   * @return companyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "37acce51-a7e3-498d-b235-5ae8f8682078", value = "")

  public UUID getCompanyId() {
    return companyId;
  }


  public void setCompanyId(UUID companyId) {
    
    
    
    this.companyId = companyId;
  }


  public HolidayCalendarsCreateNewCalendarResponseData dayOff(List<HolidayCalendarsCreateNewCalendarResponseDataDayOffInner> dayOff) {
    
    
    
    
    this.dayOff = dayOff;
    return this;
  }

  public HolidayCalendarsCreateNewCalendarResponseData addDayOffItem(HolidayCalendarsCreateNewCalendarResponseDataDayOffInner dayOffItem) {
    if (this.dayOff == null) {
      this.dayOff = new ArrayList<>();
    }
    this.dayOff.add(dayOffItem);
    return this;
  }

   /**
   * Get dayOff
   * @return dayOff
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<HolidayCalendarsCreateNewCalendarResponseDataDayOffInner> getDayOff() {
    return dayOff;
  }


  public void setDayOff(List<HolidayCalendarsCreateNewCalendarResponseDataDayOffInner> dayOff) {
    
    
    
    this.dayOff = dayOff;
  }


  public HolidayCalendarsCreateNewCalendarResponseData typeId(UUID typeId) {
    
    
    
    
    this.typeId = typeId;
    return this;
  }

   /**
   * Get typeId
   * @return typeId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "37acce51-a7e3-498d-b235-5ae8f8682078", value = "")

  public UUID getTypeId() {
    return typeId;
  }


  public void setTypeId(UUID typeId) {
    
    
    
    this.typeId = typeId;
  }


  public HolidayCalendarsCreateNewCalendarResponseData _default(Boolean _default) {
    
    
    
    
    this._default = _default;
    return this;
  }

   /**
   * Get _default
   * @return _default
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getDefault() {
    return _default;
  }


  public void setDefault(Boolean _default) {
    
    
    
    this._default = _default;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the HolidayCalendarsCreateNewCalendarResponseData instance itself
   */
  public HolidayCalendarsCreateNewCalendarResponseData putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HolidayCalendarsCreateNewCalendarResponseData holidayCalendarsCreateNewCalendarResponseData = (HolidayCalendarsCreateNewCalendarResponseData) o;
    return Objects.equals(this.id, holidayCalendarsCreateNewCalendarResponseData.id) &&
        Objects.equals(this.name, holidayCalendarsCreateNewCalendarResponseData.name) &&
        Objects.equals(this.companyId, holidayCalendarsCreateNewCalendarResponseData.companyId) &&
        Objects.equals(this.dayOff, holidayCalendarsCreateNewCalendarResponseData.dayOff) &&
        Objects.equals(this.typeId, holidayCalendarsCreateNewCalendarResponseData.typeId) &&
        Objects.equals(this._default, holidayCalendarsCreateNewCalendarResponseData._default)&&
        Objects.equals(this.additionalProperties, holidayCalendarsCreateNewCalendarResponseData.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, companyId, dayOff, typeId, _default, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HolidayCalendarsCreateNewCalendarResponseData {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    dayOff: ").append(toIndentedString(dayOff)).append("\n");
    sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
    sb.append("    _default: ").append(toIndentedString(_default)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("companyId");
    openapiFields.add("dayOff");
    openapiFields.add("typeId");
    openapiFields.add("default");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to HolidayCalendarsCreateNewCalendarResponseData
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!HolidayCalendarsCreateNewCalendarResponseData.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in HolidayCalendarsCreateNewCalendarResponseData is not found in the empty JSON string", HolidayCalendarsCreateNewCalendarResponseData.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("companyId") != null && !jsonObj.get("companyId").isJsonNull()) && !jsonObj.get("companyId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `companyId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyId").toString()));
      }
      if (jsonObj.get("dayOff") != null && !jsonObj.get("dayOff").isJsonNull()) {
        JsonArray jsonArraydayOff = jsonObj.getAsJsonArray("dayOff");
        if (jsonArraydayOff != null) {
          // ensure the json data is an array
          if (!jsonObj.get("dayOff").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `dayOff` to be an array in the JSON string but got `%s`", jsonObj.get("dayOff").toString()));
          }

          // validate the optional field `dayOff` (array)
          for (int i = 0; i < jsonArraydayOff.size(); i++) {
            HolidayCalendarsCreateNewCalendarResponseDataDayOffInner.validateJsonObject(jsonArraydayOff.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("typeId") != null && !jsonObj.get("typeId").isJsonNull()) && !jsonObj.get("typeId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `typeId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("typeId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!HolidayCalendarsCreateNewCalendarResponseData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'HolidayCalendarsCreateNewCalendarResponseData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<HolidayCalendarsCreateNewCalendarResponseData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(HolidayCalendarsCreateNewCalendarResponseData.class));

       return (TypeAdapter<T>) new TypeAdapter<HolidayCalendarsCreateNewCalendarResponseData>() {
           @Override
           public void write(JsonWriter out, HolidayCalendarsCreateNewCalendarResponseData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public HolidayCalendarsCreateNewCalendarResponseData read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             HolidayCalendarsCreateNewCalendarResponseData instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of HolidayCalendarsCreateNewCalendarResponseData given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of HolidayCalendarsCreateNewCalendarResponseData
  * @throws IOException if the JSON string is invalid with respect to HolidayCalendarsCreateNewCalendarResponseData
  */
  public static HolidayCalendarsCreateNewCalendarResponseData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, HolidayCalendarsCreateNewCalendarResponseData.class);
  }

 /**
  * Convert an instance of HolidayCalendarsCreateNewCalendarResponseData to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

