/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CheckValidationListByEmployeesAndStatusResponse;
import java.time.LocalDate;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CheckValidationApi
 */
@Disabled
public class CheckValidationApiTest {

    private static CheckValidationApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new CheckValidationApi(apiClient);
    }

    /**
     * List Check Validation By Employees and Status
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listByEmployeesAndStatusTest() throws ApiException {
        List<UUID> employeeIdsIn = null;
        String status = null;
        LocalDate from = null;
        LocalDate to = null;
        Integer limit = null;
        Integer page = null;
        CheckValidationListByEmployeesAndStatusResponse response = api.listByEmployeesAndStatus()
                .employeeIdsIn(employeeIdsIn)
                .status(status)
                .from(from)
                .to(to)
                .limit(limit)
                .page(page)
                .execute();
        // TODO: test validations
    }

}
