/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CheckTypesListTypesResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CheckTypesApi
 */
@Disabled
public class CheckTypesApiTest {

    private static CheckTypesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new CheckTypesApi(apiClient);
    }

    /**
     * List Check Types
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTypesTest() throws ApiException {
        Integer limit = null;
        Integer page = null;
        CheckTypesListTypesResponse response = api.listTypes()
                .limit(limit)
                .page(page)
                .execute();
        // TODO: test validations
    }

}
