/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.EmployeeScheduleTemplatesCreateEmployeeScheduleTemplateRequest;
import com.konfigthis.client.model.EmployeeScheduleTemplatesCreateEmployeeScheduleTemplateResponse;
import com.konfigthis.client.model.EmployeeScheduleTemplatesListTemplatesResponse;
import com.konfigthis.client.model.EmployeeScheduleTemplatesUnassignResponse;
import java.time.LocalDate;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmployeeScheduleTemplatesApi
 */
@Disabled
public class EmployeeScheduleTemplatesApiTest {

    private static EmployeeScheduleTemplatesApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new EmployeeScheduleTemplatesApi(apiClient);
    }

    /**
     * Create employee schedule template
     *
     * Assign employee to schedule template
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createEmployeeScheduleTemplateTest() throws ApiException {
        UUID employeeId = null;
        UUID scheduleTemplateId = null;
        LocalDate startDate = null;
        LocalDate endDate = null;
        EmployeeScheduleTemplatesCreateEmployeeScheduleTemplateResponse response = api.createEmployeeScheduleTemplate(employeeId, scheduleTemplateId, startDate)
                .endDate(endDate)
                .execute();
        // TODO: test validations
    }

    /**
     * List employee schedule template
     *
     * List employee schedule template
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTemplatesTest() throws ApiException {
        UUID employeeId = null;
        LocalDate from = null;
        LocalDate to = null;
        Integer limit = null;
        Integer page = null;
        EmployeeScheduleTemplatesListTemplatesResponse response = api.listTemplates(employeeId)
                .from(from)
                .to(to)
                .limit(limit)
                .page(page)
                .execute();
        // TODO: test validations
    }

    /**
     * Delete employee schedule template
     *
     * Unassign employee to schedule template
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void unassignTest() throws ApiException {
        UUID entityScheduleTemplateId = null;
        EmployeeScheduleTemplatesUnassignResponse response = api.unassign(entityScheduleTemplateId)
                .execute();
        // TODO: test validations
    }

}
