/*
 * Sesame Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import java.util.UUID;
import com.konfigthis.client.model.VacationCalendarsCreateNewCalendarRequest;
import com.konfigthis.client.model.VacationCalendarsCreateNewCalendarRequestDaysOffInner;
import com.konfigthis.client.model.VacationCalendarsCreateNewCalendarResponse;
import com.konfigthis.client.model.VacationCalendarsListCalendarsResponse;
import com.konfigthis.client.model.VacationCalendarsUpdateCalendarRequest;
import com.konfigthis.client.model.VacationCalendarsUpdateCalendarRequestDaysOffInner;
import com.konfigthis.client.model.VacationCalendarsUpdateCalendarResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VacationCalendarsApi
 */
@Disabled
public class VacationCalendarsApiTest {

    private static VacationCalendarsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new VacationCalendarsApi(apiClient);
    }

    /**
     * Create Vacation Calendar
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createNewCalendarTest() throws ApiException {
        UUID employeeId = null;
        UUID vacationConfigurationId = null;
        Integer year = null;
        List<VacationCalendarsCreateNewCalendarRequestDaysOffInner> daysOff = null;
        VacationCalendarsCreateNewCalendarResponse response = api.createNewCalendar(employeeId, vacationConfigurationId, year, daysOff)
                .execute();
        // TODO: test validations
    }

    /**
     * List Vacation Calendars
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listCalendarsTest() throws ApiException {
        UUID employeeId = null;
        List<Integer> yearIn = null;
        Integer limit = null;
        Integer page = null;
        VacationCalendarsListCalendarsResponse response = api.listCalendars()
                .employeeId(employeeId)
                .yearIn(yearIn)
                .limit(limit)
                .page(page)
                .execute();
        // TODO: test validations
    }

    /**
     * Update Vacation Calendar
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateCalendarTest() throws ApiException {
        UUID id = null;
        List<VacationCalendarsUpdateCalendarRequestDaysOffInner> daysOff = null;
        Integer maxDaysOff = null;
        VacationCalendarsUpdateCalendarResponse response = api.updateCalendar(id)
                .daysOff(daysOff)
                .maxDaysOff(maxDaysOff)
                .execute();
        // TODO: test validations
    }

}
